#!/usr/bin/env bash
DIMG=$(basename "$(pwd)")
echo "Building image ${DIMG}:"
docker build -t "${DIMG}" .
if [ "$?" == 0 ]; then
    echo "Image ${DIMG} build success!"
else
    echo "Image ${DIMG} build FAIL!"
    exit 1
fi
